### ISSUE TITLE
Hey babe wanna get hyped with pixel arts?

### ISSUE THREAD

**Issue by vipertechofficial** [redeclipse/deploy#1]
Non-Fungible-Reality-Simulation-Token --> Look https://wallet.crypto.red/gallery

Maybe, I don't have a good idea yet, yet, the name fits together and yet it can brings money, look: some 3D ideas, and I don't know what the hell what, but, some of the things you did, could help such open-source project, I bet, it is my instinct.

**Comment by vipertechofficial** [comment]
Okay, I can sponsor you with WCR for your game, if you can manage to help me with that Issue I created.

**Comment by q009** [comment]
Issue lacks any sort of valuable information here. Closing.

**Comment by qreeves** [comment]
Uh yeah, seems unintelligible to me. References to crypto tumblers on the site provided, so seems sketchy.

**Comment by vipertechofficial** [comment]
@qreeves Ok I suppose, it will only leads to new thoughts, I need to make those artistic situation a bit more like, a ninja's thing, so I will learn from what you provided in redeclipse.

**Comment by qreeves** [comment]
@vipertechofficial We can't even understand what you're saying.

**Comment by vipertechofficial** [comment]
@qreeves I am not saying anything, I am in front of my computer writing to you.
What I meant was that it (this issue on github), will lead you and me to have new thought, leading us to take independent action to  fight this new metaverse world order, either crypto red and red eclipse don't subvert the mind of the people, we do not, we build on our own products leading to individual freedom... By thus, the project of mine could be influenced by yours as well as versa.

**Comment by vipertechofficial** [comment]
@qreeves NFRSTs, are living in people's mind until they are simulated realities on computer, with poor graphics passing by the reality as we know.

Edit: I was annoyed since matrix 4 movie release, but it brought me this idea.

**Comment by q009** [comment]
I don't understand what any of this has to do with our project, Red Eclipse, which is an online arena shooter.
This is all a bunch of unrelated nonsense.

**Comment by qreeves** [comment]
@vipertechofficial I am going to guess your native language isn't English, because it is really hard to understand what you are *writing*. Other than having the word "red" in our names, I don't see a connection. It is still not clear what you want from us?

**Comment by vipertechofficial** [comment]
@qreeves Live cooperation like you take into the mind, that reality and computer simulated games are one and throughout words you can slightly superpose those two layer of information technology together.

**Comment by vipertechofficial** [comment]
@q009 The metaverse link both crypto and your game in its art related to its concept. Think Metaverse, Meta, multiple, multiply your project with mine and the sum could be greater of its part, yet, it only is a cybernetic concept.

**Comment by vipertechofficial** [comment]
@qreeves  @q009 do you trust providence or are you trying to indulge a little sense?

**Comment by qreeves** [comment]
Is there someone on your team that speaks better English? I really feel there's a language barrier going on here.

**Comment by vipertechofficial** [comment]
@qreeves No, sadly no, I am deceiving myself for that.
Let's try another time, could your game benefits to pixel arts which are embed into the concept of artistic situations? I mean, the metaverse isn't a concept well defined, visually it is games with poor graphics and game-play along with restrictions, why do we do that? Is there any reason, in the new begging of an age of reason, what reason could we use to make sense using a pixel art engine in combination with a open-source game ?

 * Could pixel art being a reason to not play RE IRL and creates mass-shooting, maybe.
 * Could a virtual training in RE helps someone doing pixel arts without being annoyed by others, maybe.
 
 Could, RE being a DOJO for creating pixel arts, like making reports of real-life events being a result.

**Comment by qreeves** [comment]
What do you want us to do? Put pixel art NFT's in the game?

**Comment by vipertechofficial** [comment]
@qreeves We can for sure, yet, the opposite was my idea, use RE as a ninja DOJO, but maybe it may need a reason, like maybe the best is to not do it, like, it has no reason for it. But it's while thinking with [TSB](https://fr.wikipedia.org/wiki/The_Shadow_Brokers) in mind, something I don't know what, maybe a mind that I have tell me you could have your RE avatar in CRYPTO RED, and aside of this APP, play with RE.

**Comment by SniperGoth** [comment]
I read it all, i still don't have any idea what this has to do with RE, at all

**Comment by vipertechofficial** [comment]
@SniperGoth Customize avatars and potentially maps with NFTs as pixel art, promote your game trough integrating RE's avatars in the wallet of crypto red for enabling "metaverse potential" into this application I refer.

EDIT: Yes I want to choose RE for my app's avatar system, and maybe help you receive money with Pixel Arts embed into RE's maps or just add a link to the avatar's DOJO training system.

**Comment by vipertechofficial** [comment]
> @SniperGoth Customize avatars and potentially maps with NFTs as pixel art, promote your game trough integrating RE's avatars in the wallet of crypto red for enabling "metaverse potential" into this application I refer.
> 
> EDIT: Yes I want to choose RE for my app's avatar system, and maybe help you receive money with Pixel Arts embed into RE's maps or just add a link to the avatar's DOJO training system.

@q009 @qreeves @SniperGoth I want to say, could it bring you support and money, if I manage to link RE's avatar inside WCR in order to use avatar to protect's user's identity AND show a link for playing RE like as if it would be a DOJO to train one's user avatar linked to it. Or maybe I should write I play Halo BTW.

**Comment by dc-redeclipse** [comment]
Just take that money and make your self a happy life. We do Red Eclipse with passion not for money or something else. Something people like you would never understand.

**Comment by qreeves** [comment]
Oh I see now. Red Eclipse is free and open source. We've committed to never having any paid features in our game, and want every person to have the same ability to customize their avatar as everyone else. As such, I don't think NFTs are a good fit for our project. You might want to find a more commercially minded project that sets out to make money.

**Comment by vipertechofficial** [comment]
@qreeves Yes, we will add 3D Avatar of Red Eclipse in Wallet Crypto Red because limitless nothing wants it, and then, add a section featuring the virtual DOJO called the DojoVerse or such, and it will be a source of advertising for your game which one can use to train's it's avatar on computer simulated situations.

**Comment by vipertechofficial** [comment]
@dc-de My passion is to create money out of thin air for fun.

**Comment by vipertechofficial** [comment]
@dc-de 

Try to apply pythagoras to remember which name you forgotten which is above them all head. from the four corners of the planet earth, gigantic cyber-anonymous are setting off to conquer new gold, aboard these computer protocols, men eager for adventure and space in search of the ultimate fortune, who do not have never dreamed of these infinite mathematical worlds, of these complex assemblages peopled with legend, or of a sudden passion, infinite and nevertheless nothingness, which would be conquered at the bend of a path behind the Pythagorean theorem, which has never wished to see the brain of his consciousness guided his steps, in the heart of the meta-universe of the mental universe of the head. This is the research and history of mysterious, algorithmic cryptocurrencies.
